apiVersion: v1
data:
  BASE_URL: {{ printf "%s%s%d%s" .Values.config.base_url ":" (int .Values.service.port) "/" }} 
  PASSWORD_SALT: "compassion_international_mission_2022m_@_SaLT"
kind: ConfigMap
metadata:
  name: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}-app-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}

---

apiVersion: v1
data:
  REDIS_SERVER: {{ .Values.config.redis_server_name | quote}}
  REDIS_SERVER_PORT: {{ .Values.redis_port | default 6379 | quote}}
kind: ConfigMap
metadata:
  name: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}-redis-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}

---

apiVersion: v1
data:
  READ_DATABASE_HOST: {{ .Values.config.database.read_node.host | quote}} 
  READ_DATABASE_USER: {{ .Values.config.database.read_node.user | quote}} 
  READ_DATABASE_NAME: {{ .Values.config.database.read_node.name | quote}} 
  WRITE_DATABASE_HOST: {{ .Values.config.database.write_node.host | quote}} 
  WRITE_DATABASE_USER: {{ .Values.config.database.write_node.user | quote}} 
  WRITE_DATABASE_NAME: {{ .Values.config.database.write_node.name | quote}} 
kind: ConfigMap
metadata:
  name: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}-db-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}


---

apiVersion: v1
data:
  SMTP_HOST: email-smtp.eu-west-1.amazonaws.com
  SMTP_USER: AKIAXRNTNANXSMVV3MXB
  SMTP_ENCRYPTION: tls
  SMTP_TCP_PORT: "587"
kind: ConfigMap
metadata:
  name: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}-smtp-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}

---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: email-scheduler-configmap
#   namespace: {{ .Values.namespace }}
# data:
#   DATABASE_HOST: SafinaToolkitSandbox-NLB-4354292b6c97b2c4.elb.eu-west-1.amazonaws.com # rds-nlb-06703b06341e9ea5.elb.eu-west-1.amazonaws.com # host.docker.internal
#   DATABASE_NAME: toolkit_TZ_sandbox # toolkit
#   DATABASE_USER: toolkit # admin
#   SMTP_HOST: email-smtp.eu-west-1.amazonaws.com
#   SMTP_USER: AKIAXRNTNANXSMVV3MXB
#   SMTP_ENCRYPTION: tls
#   SMTP_TCP_PORT: "587"

# ---

# apiVersion: v1
# data:
#   BASE_URL: {{ printf "%s%s%d%s" .Values.config.base_url ":" (int .Values.service.port) "/" }} 
#   PASSWORD_SALT: "compassion_international_mission_2022m_@_SaLT"
#   READ_DATABASE_HOST: {{ .Values.config.database.read_node.host | quote}} 
#   READ_DATABASE_USER: {{ .Values.config.database.read_node.user | quote}} 
#   REDIS_SERVER: {{ .Values.config.redis_server_name | quote}}
#   REDIS_SERVER_PORT: {{ .Values.redis_port | default 6379 | quote}}
#   WRITE_DATABASE_HOST: {{ .Values.config.database.write_node.host | quote}} 
#   WRITE_DATABASE_USER: {{ .Values.config.database.write_node.user | quote}} 
# kind: ConfigMap
# metadata:
#   name: {{ .Values.app.name }}-{{ .Values.app.environment }}
#   namespace: {{ .Values.namespace }}
#   labels:
#     app: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}

