apiVersion: v1
kind: Pod
metadata:
  labels:
    run: {{ .Values.app.name }}-{{ .Values.app.environment }}-redis
    app: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}
  name: {{ .Values.app.name }}-redis
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: redis:7.2.4
    name: {{ .Values.app.name }}-redis
    ports:
    - containerPort: {{ .Values.config.redis_port | default 6379}} 
    resources: 
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: "500m"
        memory: "800Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always