apiVersion: v1
data:
  READ_DATABASE_PASSWORD: {{ .Values.config.database.read_node.passwd }} 
  WRITE_DATABASE_PASSWORD: {{ .Values.config.database.write_node.passwd }} 
kind: Secret
metadata:
  name: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}

--- 

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}-smtp-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SMTP_PASSWORD: QkVBSzVvNFZFUWovSjlGYmJIMCtydmNiQ0U2VzZNbzdlOGprZ250M2wyQ04= 

--- 

# apiVersion: v1
# data:
#   READ_DATABASE_PASSWORD: {{ .Values.config.database.read_node.passwd }} 
#   WRITE_DATABASE_PASSWORD: {{ .Values.config.database.write_node.passwd }} 
# kind: Secret
# metadata:
#   name: {{ .Values.app.name }}-secret
#   namespace: {{ .Values.namespace }}
#   labels:
#     app: {{ .Values.app.name | required "A valid app name is required!" }}-{{ .Values.app.environment | required "A valid environment name is required!" }}
    

# --- 

# apiVersion: v1
# kind: Secret
# metadata:
#   name: email-scheduler-secret
#   namespace: {{ .Values.namespace }}
# type: Opaque
# data:
#   DATABASE_PASSWORD: QENvbXBhc3Npb24xMjM= # Q29tcGFzc2lvbjEyMw==
#   SMTP_PASSWORD: QkVBSzVvNFZFUWovSjlGYmJIMCtydmNiQ0U2VzZNbzdlOGprZ250M2wyQ04=